# PromptMQ Production Configuration
# Enterprise-grade settings for production deployment

log:
  level: "info"
  format: "json"               # Structured logging for production

server:
  bind: "0.0.0.0:1883"         # Accept connections from all interfaces
  ws-bind: "0.0.0.0:8080"      # WebSocket support
  read-timeout: "30s"
  write-timeout: "30s"
  daemon: true                 # Run as background daemon
  pid-file: "/var/run/promptmq.pid"

# MQTT Protocol Settings
mqtt:
  max-packet-size: 65535
  max-client-id-len: 65535
  max-topic-len: 65535
  max-qos: 2
  keep-alive: 60
  max-inflight: 20
  max-connections: 10000       # High connection limit for production
  retain-available: true
  wildcard-available: true
  shared-sub-available: true

# Storage Configuration - Production Optimized
storage:
  data-dir: "/var/lib/promptmq/data"
  
  # SQLite Configuration - Production performance
  sqlite:
    cache-size: 100000         # 100k pages (~400MB cache)
    temp-store: "MEMORY"       # Store temp tables in memory
    mmap-size: 536870912       # 512MB memory-mapped I/O
    busy-timeout: 30000        # 30 second timeout
    synchronous: "NORMAL"      # Good balance for production
    journal-mode: "WAL"        # WAL mode for ACID compliance
    foreign-keys: true         # Enable integrity constraints
    
  # Cleanup Settings - Production retention
  cleanup:
    max-message-age: "24h"     # 24-hour message retention
    check-interval: "1h"       # Check every hour
    batch-size: 1000           # Process in batches

# Clustering Configuration
cluster:
  enabled: false               # Enable for multi-node deployment
  bind: "0.0.0.0:7946"
  peers: []                    # Add cluster peer addresses
  # node-id: "promptmq-01"     # Unique node identifier

# Metrics & Monitoring
metrics:
  enabled: true
  bind: "0.0.0.0:9090"         # Prometheus metrics endpoint
  path: "/metrics"